### ISSUE TITLE
what is the difference between your dynamic implemetion of rnn and tf.nn.dynamic_rnn function ?

### ISSUE THREAD

**Issue by underspirit** [KnHuq/Dynamic-Tensorflow-Tutorial#2]
https://www.tensorflow.org/versions/r0.10/api_docs/python/nn.html#dynamic_rnn

**Comment by KnHuq** [comment]
@	underspirit, Thanks for your important question. There are not much difference from their dynamic rnn. But their implementation is faster and perfect than this one. It is for learning purpose, how you create dynamic model with tensorflow. Suppose when you want to build your own model dynamically, you can not implement others API. I suggest anyone to use tenosrflow API rather than mine to implement exisitng models. My repo is for learning how to implement it. Tensorflow did not support dynamic sequence length before like theano, so it was problematic then for many of us, to implement new models with new equations dynamically with tensorflow. So my implementations shows you how you can handle those challenges.  I hope it helps you.

**Comment by underspirit** [comment]
Thanks a lot for for your explanation and your repo.

**Comment by paduvi** [comment]
Thanks for your implement. It help me a lot how to build a custom RNN.
I still have a question, how can I define sequence length to force tensorflow stop more calculate and return exact last output instead of last fixed index.

tf.nn.dynamic_rnn has attribute `sequence_length` to do this. How can I implement it myself?
